/* ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ;
; Copyright © 2009 Edgeware Technologies (India) Pvt Ltd ;
; ;
; This source code contains the intellectual property ;
; of its copyright holder(s), and is made available ;
; under a license. If you do not know the terms of ;
; the license, please stop and do not read further. ;
; ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
*/

package com.etipl.pms;

import com.etipl.pms.datalayer.GetSystemConfig;


import com.etipl.pms.utilities.Utiles;
import java.awt.Dimension;
import java.awt.Toolkit;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrator
 */
public class LoginScreen extends javax.swing.JFrame {
   
    /** Creates new form LoginScreen */
    public static LoginScreen ls;
    public static String presentuser="";
    private static String sip="", sport="", dbname="", uname="", passwd="" ;
    public static String user="",category="";

    public LoginScreen() {
        initComponents();
        
        Dimension frameDimension = getSize();
        
		// position the topFrame
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        if (frameDimension.height > screenSize.height)
            {
            frameDimension.height = screenSize.height;
        }

            if (frameDimension.width > screenSize.width)
            {
                frameDimension.width = screenSize.width;
        }
        setLocation((screenSize.width - frameDimension.width) / 2,
                    ((screenSize.height - frameDimension.height) / 2)-30);

            tfuname.requestFocus();
            connect_Setting("P");
   }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfuname = new javax.swing.JTextField();
        jbsubmit = new javax.swing.JButton();
        jbcancel = new javax.swing.JButton();
        tfpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VistA-Edge™ Practice Management System : Login Screen");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("User Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        tfuname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfunameKeyTyped(evt);
            }
        });
        jPanel1.add(tfuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jbsubmit.setMnemonic('o');
        jbsubmit.setText("OK");
        jbsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jbsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 70, 25));

        jbcancel.setMnemonic('c');
        jbcancel.setText("Cancel");
        jbcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 25));

        tfpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpassKeyTyped(evt);
            }
        });
        jPanel1.add(tfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 250, 120));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Edgeware Technologies - www.vista-edge.com");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 280, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16));
        jLabel5.setText("Practice Management System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("support@vista-edge.com");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16));
        jLabel1.setText("VistA-Edge");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("™");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 20, 10, -1));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelActionPerformed
// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbcancelActionPerformed

    private void tfunameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfunameKeyTyped
// TODO add your handling code here:
        if (evt.getKeyChar()=='\n')
            tfpass.requestFocus();
    }//GEN-LAST:event_tfunameKeyTyped

    private void jbsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsubmitActionPerformed
// TODO add your handling code here:
        submit_button_pressed();
    }//GEN-LAST:event_jbsubmitActionPerformed

    private void tfpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpassKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar()=='\n')
           submit_button_pressed();
    }//GEN-LAST:event_tfpassKeyTyped
    
    private void submit_button_pressed()
    {
        try
        {            
            Class.forName("com.mysql.jdbc.Driver");
            String url ="jdbc:mysql://"+sip+":"+sport+"/"+dbname;
            Connection con =  DriverManager.getConnection(url,uname, passwd);

            Statement stmt = con.createStatement();
            String username=tfuname.getText();
            presentuser=username;
            String pass=tfpass.getText();
            String sqlString = "select * from USERS where UNAME = '"+username+"'" ;
            ResultSet rs=stmt.executeQuery(sqlString);
            rs.first();
            if(rs.getRow()!=0)
            {
                if (rs.getString("password").equalsIgnoreCase(Utiles.hashPassword(pass)))
                {
                    setVisible(false);
                    category=rs.getString("CATEGORY");
                    user=rs.getString("uname");
                    System.out.print(category);
                    new MDI().setVisible(true);             
                }
                else
                {
                    JOptionPane.showMessageDialog(ls, "Password is incorrect, Please enter your password again.", "Login error", JOptionPane.ERROR_MESSAGE);
                    tfpass.setText("");
                    tfpass.requestFocus();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(ls, "Check your username", "Login error", JOptionPane.ERROR_MESSAGE);
                tfuname.setText("");
                tfpass.setText("");        
                tfuname.requestFocus();
            }
        }        
        catch(Exception sql){sql.printStackTrace();}               
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }
    
   private static void connect_Setting(String which)
   {
           GetSystemConfig ob=new GetSystemConfig();
           dbname=ob.getDbName(which);
           sip=ob.getDbIp(which);
           sport=ob.getDbPort(which);
           uname=ob.getUserName(which);
           passwd=ob.getPassword(which);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JButton jbcancel;
    public static javax.swing.JButton jbsubmit;
    public static javax.swing.JPasswordField tfpass;
    public static javax.swing.JTextField tfuname;
    // End of variables declaration//GEN-END:variables
    
}
