/* ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ;
; Copyright © 2009 Edgeware Technologies (India) Pvt Ltd ;
; ;
; This source code contains the intellectual property ;
; of its copyright holder(s), and is made available ;
; under a license. If you do not know the terms of ;
; the license, please stop and do not read further. ;
; ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
*/


package com.etipl.pms.reports.AZSlidingFee;

import com.etipl.pms.MDI;
import com.etipl.pms.datalayer.Reports;
import com.etipl.pms.PatientList;
import com.etipl.pms.SearchCriteria;
import com.etipl.pms.utilities.Utiles;
import java.awt.Dimension;
import java.awt.Toolkit;
import org.gui.JCalendarCombo;

public class AZReport extends javax.swing.JFrame {

    /** Creates new form AZReport */
    public AZReport() {
        initComponents();
        setVisible(true);
         
        screenDisplay();        
        this.butReport.setEnabled(false);
        this.txtHRN.requestFocus();
        this.panelSummary.setVisible(false);
        radioSum.setVisible(false);
        sdate.setDateFormat(JCalendarCombo.MONTH, JCalendarCombo.DAY, JCalendarCombo.YEAR_BIG, '/');
        edate.setDateFormat(JCalendarCombo.MONTH, JCalendarCombo.DAY, JCalendarCombo.YEAR_BIG, '/');
        txtHRN.setText(PatientList.globalhrn);
        getClaimNos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    private void screenDisplay(){
    Dimension frameDimension = getSize();

		// position the topFrame
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        if (frameDimension.height > screenSize.height)
        {
		frameDimension.height = screenSize.height;
        }

        if (frameDimension.width > screenSize.width)
        {
			frameDimension.width = screenSize.width;
        }
        setLocation((screenSize.width - frameDimension.width) / 2,
				(screenSize.height - frameDimension.height) / 2);
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        butReport = new javax.swing.JButton();
        panelStatememt = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtHRN = new javax.swing.JTextField();
        cmbClaimID = new javax.swing.JComboBox();
        panelSummary = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        sdate = new org.gui.JCalendarCombo();
        jLabel2 = new javax.swing.JLabel();
        edate = new org.gui.JCalendarCombo();
        radioStms = new javax.swing.JRadioButton();
        radioSum = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        butSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AZSliding  Fee Reports");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText(" AZSliding Fee Reports");

        butReport.setText("Generate Report");
        butReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReportActionPerformed(evt);
            }
        });
        butReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                butReportKeyPressed(evt);
            }
        });

        panelStatememt.setBorder(javax.swing.BorderFactory.createTitledBorder("Statement"));

        jLabel4.setText("HRN:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Claim No:");

        txtHRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHRNActionPerformed(evt);
            }
        });
        txtHRN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHRNFocusLost(evt);
            }
        });
        txtHRN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHRNKeyPressed(evt);
            }
        });

        cmbClaimID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClaimIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStatememtLayout = new javax.swing.GroupLayout(panelStatememt);
        panelStatememt.setLayout(panelStatememtLayout);
        panelStatememtLayout.setHorizontalGroup(
            panelStatememtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatememtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHRN, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbClaimID, 0, 151, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelStatememtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStatememtLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(jComboBox2, 0, 0, Short.MAX_VALUE)
                    .addGap(92, 92, 92)))
        );
        panelStatememtLayout.setVerticalGroup(
            panelStatememtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatememtLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelStatememtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbClaimID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(panelStatememtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStatememtLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelSummary.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary"));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Start Date ");

        jLabel2.setText("End Date ");

        javax.swing.GroupLayout panelSummaryLayout = new javax.swing.GroupLayout(panelSummary);
        panelSummary.setLayout(panelSummaryLayout);
        panelSummaryLayout.setHorizontalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jComboBox4, 0, 0, Short.MAX_VALUE)
                .addGap(74, 74, 74))
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(edate, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSummaryLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
        );
        panelSummaryLayout.setVerticalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSummaryLayout.createSequentialGroup()
                        .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(radioStms);
        radioStms.setSelected(true);
        radioStms.setText("Statement");
        radioStms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStmsActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioSum);
        radioSum.setText("Summary");
        radioSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSumActionPerformed(evt);
            }
        });

        butSearch.setText("Search Patient");
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStatememt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(radioStms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(radioSum)
                .addGap(58, 58, 58))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(butReport, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSum)
                    .addComponent(radioStms))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatememt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSearch)
                    .addComponent(butReport))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void getReport(){
    try{
        AZSlidingStatement az=new AZSlidingStatement();

        if(radioStms.isSelected()){
            String claimNo=cmbClaimID.getSelectedIndex()==-1?"":
                           cmbClaimID.getSelectedItem().toString();
            az.generateAZSlidingStms(claimNo);
        }

        if(radioSum.isSelected()){
             az.generateAZSlidingSum(
             Utiles.convertUSDatetoMysql(sdate.getSelectedDate()),
             Utiles.convertUSDatetoMysql(edate.getSelectedDate()));
        }
    }catch(Exception e){e.printStackTrace();}
}

private void butReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReportActionPerformed
        // TODO add your handling code here:
        getReport();
}//GEN-LAST:event_butReportActionPerformed

private void butReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butReportKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == '\n'){
            getReport();
        }
}//GEN-LAST:event_butReportKeyPressed

private void getClaimNos(){
    try{
        Reports r=new Reports();
        String temp[];
        temp=r.getClaimNosfromCMS_CPTs(this.txtHRN.getText());
        if(temp!=null){
            this.cmbClaimID.setModel(new javax.swing.DefaultComboBoxModel(temp));            
                this.butReport.setEnabled(true);             
                this.txtHRN.setText("");
                this.butReport.requestFocus();
        }
    }catch(Exception e){e.printStackTrace();}
    }
    
    private void radioSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSumActionPerformed
        // TODO add your handling code here:
    try{
        if(radioSum.isSelected()){
            this.panelSummary.setVisible(true);
            this.panelStatememt.setVisible(false);
        }        
    }catch(Exception e){e.printStackTrace();}
}//GEN-LAST:event_radioSumActionPerformed

    private void radioStmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStmsActionPerformed
        // TODO add your handling code here:
        try{
        if(this.radioStms.isSelected()){
            this.panelStatememt.setVisible(true);
            this.panelSummary.setVisible(false);
        }        
    }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_radioStmsActionPerformed

    private void txtHRNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHRNKeyPressed
        // TODO add your handling code here:
    try{
        if(evt.getKeyCode()==10){
            getClaimNos();
        }
    }catch(Exception e){e.printStackTrace();}

    }//GEN-LAST:event_txtHRNKeyPressed

    private void txtHRNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHRNFocusLost
        // TODO add your handling code here:
        getClaimNos();
    }//GEN-LAST:event_txtHRNFocusLost

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        // TODO add your handling code here:
    try{
        if(MDI.searchCriteria==null){
            SearchCriteria sp=new SearchCriteria();
            PatientList.whichForm = PatientList.sAZReport;
            this.dispose();
        }
    }catch(Exception e){e.printStackTrace();}
}//GEN-LAST:event_butSearchActionPerformed

    private void cmbClaimIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClaimIDActionPerformed
        // TODO add your handling code here:
        if(this.cmbClaimID.getSelectedIndex()!=-1){
            this.butReport.setEnabled(true);
            this.butReport.requestFocus();
        }else{
            this.butReport.setEnabled(false);
        }
    }//GEN-LAST:event_cmbClaimIDActionPerformed

    private void txtHRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHRNActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
     try{
         if(this.getDefaultCloseOperation()==MDI.defaultWindowClose){
            MDI.azSlidingReport=null;
         }
     }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_formWindowClosed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AZReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butReport;
    private javax.swing.JButton butSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbClaimID;
    private org.gui.JCalendarCombo edate;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelStatememt;
    private javax.swing.JPanel panelSummary;
    private javax.swing.JRadioButton radioStms;
    private javax.swing.JRadioButton radioSum;
    private org.gui.JCalendarCombo sdate;
    private javax.swing.JTextField txtHRN;
    // End of variables declaration//GEN-END:variables

}
